### PR TITLE
Add type checking, eslint, and prettier to `npm test`.

### PR DESCRIPTION
**Pull request by SamWilsn**
Because this pull request reformats everything, I'd recommend going one commit at a time.

### CODE REVIEW

**Comment by SamWilsn** [comment]
Hm, looks like `bun test` doesn't respect `package.json`. How would you suggest getting eslint/prettier to run in CI?

**Comment by Pandapip1** [comment]
> Hm, looks like bun test doesn't respect package.json. How would you suggest getting eslint/prettier to run in CI?

IIRC `bun run test` should run the `test` script.

**Review by Pandapip1 — APPROVED** [review]
If this passes tests, I'll have this merged.

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Type checking failed

**Review by Pandapip1 — CHANGES_REQUESTED** [review]
Prettier is failing

**Comment by SamWilsn** [comment]
Ah, yeah. Because I'm not updating the bun lock file, it's using the old dependencies cache. Can you generate a new lockfile?

**Review by Pandapip1 — APPROVED** [review]
LGTM. Tests passed locally.

**Pull request merged**
